# A script to generate csvs with hippocampal R1/volume data and demographics for analysis

library(dplyr)
library(stringr)
library(arrow)

########### Combine R1 Data and Demographics for Final Study Sample ################

# Demographics data 
demographics <- read.csv("/Volumes/Hera/Projects/hippocampal_myelin/sample_info/7T_MP2RAGE/finalsample_demographics.csv") #generated by /sample_construction/finalsample_hippocampalmyelin.Rmd

# Hippocampal R1 (whole hippocampus and head-body-tail)
hippocampal.R1 <- read.csv("/Volumes/Hera/Projects/hippocampal_myelin/output_measures/7T_MP2RAGE/hippocampal_R1/hippocampus_meanR1_aseg_stats.csv")
hippocampal.R1 <- hippocampal.R1 %>% mutate(subject_id = str_extract(fs_subid, "sub-[0-9]+"), session_id = str_extract(fs_subid, "ses-[0-9]+"))

lh.HBT.R1 <- read.csv("/Volumes/Hera/Projects/hippocampal_myelin/output_measures/7T_MP2RAGE/hippocampal_R1/lh.hippocampus_meanR1_HBT_stats.csv")
rh.HBT.R1 <- read.csv("/Volumes/Hera/Projects/hippocampal_myelin/output_measures/7T_MP2RAGE/hippocampal_R1/rh.hippocampus_meanR1_HBT_stats.csv")
HBT.R1 <- merge(lh.HBT.R1, rh.HBT.R1, by = "fs_subid", sort = F)

# Hippocampal Volume (whole hippocampus and head-body-tail) and eTIV 
hippocampal.eTIV.volume <- read_parquet("/Volumes/Hera/Projects/corticalmyelin_development/BIDS/derivatives/surface_metrics/7T_BrainMechanisms_brainmeasures.parquet") %>% 
                   select(subject_id, session_id, Left_Hippocampus_Volume_mm3, Right_Hippocampus_Volume_mm3, Cortex_CortexVol, EstimatedTotalIntraCranialVol_eTIV)
hippocampal.eTIV.volume$session_id <- sub("\\..*$", "", hippocampal.eTIV.volume$session_id)

lh.HBT.volume <- read.csv("/Volumes/Hera/Projects/hippocampal_myelin/output_measures/7T_MP2RAGE/hippocampal_volume/lh.hippocampus_volume_HBT_stats.csv")
rh.HBT.volume <- read.csv("/Volumes/Hera/Projects/hippocampal_myelin/output_measures/7T_MP2RAGE/hippocampal_volume/rh.hippocampus_volume_HBT_stats.csv")
HBT.volume <- merge(lh.HBT.volume, rh.HBT.volume, by = "fs_subid", sort = F)

# Combine and save for final sample
hippocampal.R1 <- left_join(hippocampal.R1, HBT.R1, by = "fs_subid") # whole and HBT R1 measures
hippocampal.R1 <- left_join(hippocampal.R1, HBT.volume, by = c("fs_subid"))
hippocampal.R1 <- left_join(hippocampal.R1, hippocampal.eTIV.volume, by = c("subject_id", "session_id"))
hippocampal.R1 <- left_join(demographics, hippocampal.R1, by = c("subject_id", "session_id"))
write.csv(hippocampal.R1, "/Volumes/Hera/Projects/hippocampal_myelin/output_measures/7T_MP2RAGE/hippocampal_R1_demographics.csv", quote = F, row.names = F)
